Repository Swift-Money-Management-Team-App/MoneyManagementApp, pull requests merged in 2024-11, with the labels that each got.

#37 Chore: Removed file that shouldn't be tracked
  MoneyManagement App.xcodeproj/project.xcworkspace/xcuserdata/rafaelrikiogawaosiro.xcuserdatad/UserInterfaceState.xcuserstate
  MoneyManagement App.xcodeproj/project.xcworkspace/xcuserdata/raquel.xcuserdatad/UserInterfaceState.xcuserstate
Labels: chore

#40 Chore: Removing unused files and add Pull Request Template
  .github/pull_request_template.md
  MoneyManagement App/Helper/DateFormatter.swift
  MoneyManagement App/View/Shared/TopTitle.swift
  MoneyManagement App/View/Views/AccountDetail/Components/SectionTitle.swift
  MoneyManagement App/View/Views/AccountDetail/EditFinancialInstitution.swift
  MoneyManagement App/View/Views/Content/ContentView.swift
  MoneyManagement App/View/Views/Content/ContentViewModel.swift
  MoneyManagement App/View/Views/Content/UsernameView.swift
Labels: chore

#45 Feat: Payment method screen
  MoneyManagement App.xcodeproj/project.pbxproj
  MoneyManagement App/Application/MoneyManagement_AppApp.swift
  MoneyManagement App/View/Views/Home/HomeView.swift
  MoneyManagement App/View/Views/PaymentMethod/DetailPaymentMethodView.swift
  MoneyManagement App/View/Views/PaymentMethod/EditPaymentMethodView.swift
  MoneyManagement App/View/Views/PaymentMethod/PaymentMethodView.swift
Labels: feat

#54 Chore: Adicionar o chore request template para o Github Projects
  .github/ISSUE_TEMPLATE/chore_request.md
Labels: chore

#61 Fix: Navigation
  MoneyManagement App/Application/MoneyManagement_AppApp.swift
  MoneyManagement App/Model/EarningCategory.swift
  MoneyManagement App/Model/ExpenseCategory.swift
  MoneyManagement App/Model/Method.swift
  MoneyManagement App/Model/Movement.swift
  MoneyManagement App/Utility/Navigation.swift
  MoneyManagement App/View/Views/BankAccount/BankAccountView.swift
  MoneyManagement App/View/Views/BankAccount/BankAccountViewModel.swift
  MoneyManagement App/View/Views/Home/HomeView.swift
  MoneyManagement App/View/Views/Home/HomeViewModel.swift
  MoneyManagement App/View/Views/Settings/Components/AboutUs.swift
  MoneyManagement App/View/Views/Settings/Components/PrivacyPolicy.swift
  MoneyManagement App/View/Views/Settings/Components/Terms.swift
  MoneyManagement App/View/Views/Settings/SettingsView.swift
  MoneyManagement App/View/Views/Settings/SettingsViewModel.swift
Labels: bug
